
spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint:
        bucket: microservice-mall
server:
  port: 30000

